### ISSUE TITLE
the2019ncov.com Timeline (GMT) is broken

### ISSUE THREAD

**Issue by GodofWar9000** [sorxrob/2019-ncov-api#2]
When you go to https://the2019ncov.com - and you scroll down, the timeline stops updating on February 29, 2020.

**Comment by sorxrob** [comment]
Yeah, have to remove it or add another feature. Pretty busy right now

**Comment by GodofWar9000** [comment]
Looking forward to that fix, and any updates you make when you get time. It's a nice frontend! I would also suggest using the Johns Hopkins data set which is up to date: https://github.com/CSSEGISandData/COVID-19

**Comment by GodofWar9000** [comment]
Nvm, I see that you are using the Johns Hopkins data - disregard that. What frameworks did you use for the frontend?
